name: Release and deploy Todo

on:
  push:
    branches:
    - "release/*"

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25.1.0
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJ_ID }}
        vercel-args: "--prod"
